//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Domain
{
    using System;
    using System.Collections.Generic;

    public partial class Customer
    {
        public Customer()
        {
            this.CustomerAddress = new HashSet<CustomerAddress>();
            this.SalesOrderHeader = new HashSet<SalesOrderHeader>();
        }
        [HiddenInput(DisplayValue = false)]
        public int CustomerID { get; set; }
        [HiddenInput(DisplayValue = false)]
        public bool NameStyle { get; set; }
        [HiddenInput(DisplayValue = false)]
        public string Title { get; set; }
        [Required(ErrorMessage = "*")]
        public string FirstName { get; set; }
        [HiddenInput(DisplayValue = false)]
        public string MiddleName { get; set; }
        [Required(ErrorMessage = "*")]
        public string LastName { get; set; }
        [HiddenInput(DisplayValue = false)]
        public string Suffix { get; set; }
        [HiddenInput(DisplayValue = false)]
        public string CompanyName { get; set; }
        [HiddenInput(DisplayValue = false)]
        public string SalesPerson { get; set; }
        [Required(ErrorMessage = "*")]
        [Remote("CheckForExist", "Registration", ErrorMessage = "This email are used")]
        public string EmailAddress { get; set; }
        public string Phone { get; set; }
        [HiddenInput(DisplayValue = false)]
        public string PasswordHash { get; set; }
        [Required(ErrorMessage = "*")]
        public string PasswordSalt { get; set; }
        [HiddenInput(DisplayValue = false)]
        public System.Guid rowguid { get; set; }
        [HiddenInput(DisplayValue = false)]
        public System.DateTime ModifiedDate { get; set; }
        

        public virtual ICollection<CustomerAddress> CustomerAddress { get; set; }
        public virtual ICollection<SalesOrderHeader> SalesOrderHeader { get; set; }
    }
}
