//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Domain
{
    using System;
    using System.Collections.Generic;

    public partial class Product
    {
        public Product()
        {
            this.SalesOrderDetail = new HashSet<SalesOrderDetail>();
        }
        [HiddenInput(DisplayValue = false)]
        public int ProductID { get; set; }
        [Required(ErrorMessage = "*")]
        public string Name { get; set; }
        [Required(ErrorMessage = "*")]
        public string ProductNumber { get; set; }
        [HiddenInput(DisplayValue = false)]
        public string Color { get; set; }
        [Required(ErrorMessage = "*")]
        [Range(0.01,double.MaxValue, ErrorMessage = "*")]
        public decimal StandardCost { get; set; }
        [HiddenInput(DisplayValue = false)]
        public decimal ListPrice { get; set; }
        [HiddenInput(DisplayValue = false)]
        public string Size { get; set; }
        [HiddenInput(DisplayValue = false)]
        public Nullable<decimal> Weight { get; set; }
        [HiddenInput(DisplayValue = false)]
        public Nullable<int> ProductCategoryID { get; set; }
        [HiddenInput(DisplayValue = false)]
        public Nullable<int> ProductModelID { get; set; }
        [HiddenInput(DisplayValue = false)]
        public System.DateTime SellStartDate { get; set; }
        [HiddenInput(DisplayValue = false)]
        public Nullable<System.DateTime> SellEndDate { get; set; }
        [HiddenInput(DisplayValue = false)]
        public Nullable<System.DateTime> DiscontinuedDate { get; set; }
        public byte[] ThumbNailPhoto { get; set; }
        [HiddenInput(DisplayValue = false)]
        public string ThumbnailPhotoFileName { get; set; }
        [HiddenInput(DisplayValue = false)]
        public System.Guid rowguid { get; set; }
        [HiddenInput(DisplayValue = false)]
        public System.DateTime ModifiedDate { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductModel ProductModel { get; set; }
        public virtual ICollection<SalesOrderDetail> SalesOrderDetail { get; set; }
    }
}
